<?php

namespace ContainerHIEpGcB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilmsTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FilmsType' shared autowired service.
     *
     * @return \App\Form\FilmsType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FilmsType.php';

        return $container->privates['App\\Form\\FilmsType'] = new \App\Form\FilmsType();
    }
}
