<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMZ86LqN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMZ86LqN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMZ86LqN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMZ86LqN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMZ86LqN\App_KernelDevDebugContainer([
    'container.build_hash' => 'MZ86LqN',
    'container.build_id' => 'f292beaf',
    'container.build_time' => 1643229536,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMZ86LqN');
